### ISSUE TITLE
PropTypes should be defined statically

### ISSUE THREAD

**Issue by burnnat** [jonjaques/react-loaders#1]
When using the `Loader` component, React outputs the following warning message:

> Warning: propTypes was defined as an instance property on Loader. Use a static property to define propTypes instead.

(This is with React 0.13.1, though I doubt it matters.)

**Comment by jonjaques** [comment]
Fixed in 1.0.2.

It's quite irritating they throw these errors, because so far as I can tell this is the way you're [supposed to do it](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es6-classes) until ES7 supports static properties.
