### ISSUE TITLE
Loader renders but here is no animation

### ISSUE THREAD

**Issue by UX-Unicorn** [jonjaques/react-loaders#15]
The loader renders but there is no animation. When I look in the dev tools the css is being applied but there is still no animation. Can someone help with this?

**Comment by jonjaques** [comment]
Will take a look at this later today. In the meantime can you try @2.1.1?

**Comment by boonhui-lai** [comment]
@2.1.1 does not work either 😢

**Comment by jonjaques** [comment]
@UX-Unicorn @boonhui-lai Are import `loaders.css` into your own stylesheet? All this component does is pump out divs with the right classes.

**Comment by boonhui-lai** [comment]
I'm using it as per your documentation

style.scss
```
@import '~loaders.css/src/animations/line-scale.scss';

.loader-hidden {
  display: none;
}
.loader-active {
  display: block;
}
```
index.js
```
import {Loader} from 'react-loaders';
import style from './styles/style.scss';
import {render} from 'react-dom';
import React from 'react';

render(
    <Loader type="line-scale" active={true} />,
    document.getElementById('app'),
);
```
webpack.config.js
```
...
module: {
        loaders: [
            {
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    presets: ['react', 'es2015', 'stage-1']
                }
            },
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract({fallback:'style-loader',use:'css-loader!sass-loader'})
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin({ filename: 'style.css', disable: false, allChunks: true })
    ],
...
```
index.html
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>React In Action</title>
    <link rel="stylesheet" type="text/css" href="/style.css" />
</head>
<body>
<div id="app"></div>
<script src="/bundle.js"></script>
</body>
</html>
```

**Comment by jonjaques** [comment]
Hmm, minus testing the direct npm import from loaders.css; this appears to be working for me: 
https://www.webpackbin.com/bins/-KgV-ArRTILqyDaMqSGs

For whatever reason I can't get webpackbin to import loaders.css so I just manually copied in the code. You may have to do the same. One time long ago, I read about the webpack css loader being able to `@import ~package-name`, however I can't seem to find docs on that behavior right now.

Question: do you happen to be looking at this on a white background?

**Comment by boonhui-lai** [comment]
You are right, this is embarrassing. I left out

```
$my-brand-color : red;

$primary-color: $my-brand-color;
```
