### ISSUE TITLE
Latest version of react gives PropTypes warning

### ISSUE THREAD

**Issue by keeth** [jonjaques/react-loaders#16]
With React 15.5, importing PropTypes from React is deprecated in favor of importing from the new 'prop-types' package.

See this link: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

Thus, using react-loaders with the latest version of React gives a deprecation warning in the console.

**Comment by jharris4** [comment]
Created a PR: https://github.com/jonjaques/react-loaders/pull/17

**Comment by jonjaques** [comment]
Thanks!
