### ISSUE TITLE
Getting error while using react-loaders

### ISSUE THREAD

**Issue by juhiMatta** [jonjaques/react-loaders#20]
Hi..

I did all the steps which you specify. 
First of all I did : npm install --save react-loaders loaders.css

Then, I created one js file. It includes 
`import {Loader} from 'react-loaders';

function renderLoader() {
  return <Loader type="line-scale" active />
}
`
Then I created .scss file. It includes

`$primary-color: #10CEA1;
@import 'loaders.css/src/animations/line-scale.scss';

.loader-hidden {
  display: none;
}
.loader-active {
  display: block;
}
`

But I am getting error : 
**File to import not found or unreadable: loaders.css/src/animations/line-scale.scss.\nParent style**
Thanks in Advance

**Comment by TheSharpieOne** [comment]
Try `@import '~loaders.css/src/animations/line-scale.scss';` the `~` tell it to look in the node_modules directory.

**Comment by jonjaques** [comment]
Added a note in readme. The way I was requiring it previously was to add loaders.css into the load path for Sass directly.
