### ISSUE TITLE
So many errors before it works

### ISSUE THREAD

**Issue by Y-Taras** [jonjaques/react-loaders#22]
I added component   
`yarn add react-loaders loaders.css `
imported and added to my component 
`<Loader type="line-scale" active />`.
In result got an error 
![screenshot from 2017-09-18 17 59 13](https://user-images.githubusercontent.com/8538134/30548725-97f927ee-9c9b-11e7-8cfe-6398e9d3ede8.png)
Then added `babel-preset-es2015` by typing `yarn add babel-preset-es2015` 
got a warning  
![screenshot from 2017-09-18 17 59 34](https://user-images.githubusercontent.com/8538134/30548848-ebcc6818-9c9b-11e7-9ab9-dc71bd4d5031.png)
nevertheless added it to my `.babelrc` file.
Then got another error: 
![screenshot from 2017-09-18 17 58 40](https://user-images.githubusercontent.com/8538134/30548889-0633980c-9c9c-11e7-8bdf-a286f5e0cc85.png)
_What am I doing wrong?_

**Comment by jonjaques** [comment]
Hmm, so you shouldn't actually need to babel to use this at all. My guess is the devDependencies (which *are* out of date) are triggering that warning.

Will see about getting those bumped. Sorry for any confusion!

**Comment by Y-Taras** [comment]
### .babelrc  
```
{
	"presets": [
		"react",
		["env", {
			"targets": {
				"browsers": "last 2 versions"
			},
			"loose": true,
			"modules": false
		}]
	],
  "plugins": [
    "react-hot-loader/babel",
    "babel-plugin-transform-class-properties",
    "sitrep"
      ],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs"
      ]
    }
  }
}
```

**Comment by Y-Taras** [comment]
### webpack.config.js  
```
module.exports = {
  context: __dirname,
  entry: [
    'react-hot-loader/patch',
    'webpack-dev-server/client?http://localhost:8080',
    'webpack/hot/only-dev-server',
    './js/ClientApp.jsx'
  ],
  devtool: 'cheap-eval-source-map',
  output: {
    path: path.join(__dirname, 'public'),
    filename: 'bundle.js',
    publicPath: '/public/'
  },
  devServer: {
    hot: true,
    publicPath: '/public/',
    historyApiFallback: true
  },
  resolve: {
    extensions: ['.js', '.jsx', '.json']
  },
  stats: {
    colors: true,
    reasons: true,
    chunks: true
  },
  plugins: [new webpack.HotModuleReplacementPlugin(), new webpack.NamedModulesPlugin()],
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.jsx?$/,
        loader: 'eslint-loader',
        exclude: /node_modules/
      },
      {
        test: /\.jsx?$/,
        loader: 'babel-loader'
      }
    ]
  }
};
```

**Comment by jonjaques** [comment]
Yeah, I would suggest adding `exclude: /node_modules/` to your babel-loader rule. As configured you're running all your node_modules through babel which is generally not recommended or necessary.

**Comment by jonjaques** [comment]
Closing this as I believe it is a config issue.
