### ISSUE TITLE
loaderr-undefined

### ISSUE THREAD

**Issue by Und3Rdo9** [jonjaques/react-loaders#25]
Hi, 
I'm calling the Loader as follows: 
```<Loader type='ball-grid-pulse' active />```
but get the following output:
```<div class="loader loader-undefined loader-active"><div class="loader-inner ball-grid-pulse"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div></div>```

however the default line-scale type works for some reason. I'm importing the entire css file and have visible color set.

**Comment by Und3Rdo9** [comment]
never mind, it seemed that an import was failing but no errors showed.

**Comment by traxx10** [comment]
Still getting the same error

**Comment by mattdamon108** [comment]
I have same error. Does *.css needs to be loaded?

**Comment by johnreytanquinco** [comment]
also getting the same error message.

index.js

```
import React from 'react';
import { render } from 'react-dom';
import Chart from './Chart';
import Loader from 'react-loaders';
...
...
  render() {
    if (this.state.data == null) {
      return <Loader type="line-scale"/>
    }
  }
```

theme.scss
```

/*------------- #THEME-STYLES --------------*/

@import "theme-styles/_variables";
@import "theme-styles/_bootstrap-customization";
@import "loaders.css/src/animations/line-scale.scss";

```
_bootstrap-customization.scss
```
/*------------- #BOOTSTRAP-CUSTOMIZATION --------------*/

.loader-hidden {
  display: none;
}
.loader-active {
  display: block;
}
...
```

webpack.config.js
```
module.exports = {
  entry: ['./js/index.js'],
  output: {
    path: __dirname + "/js/",
    filename: 'favorite.bundle.js'
  },
  module: {
    loaders: [
      {test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'},
      { test: /\.css$/, loader: "style-loader!css-loader" }
    ]
  }
};

```
Result:
`<div data-reactroot="" class="loader loader-undefined loader-active"><div class="loader-inner ball-pulse"><div></div><div></div><div></div></div></div>
`
