### ISSUE TITLE
Div moves around when scale property is used to size loader

### ISSUE THREAD

**Issue by aguynamedben** [jonjaques/react-loaders#27]
Hi, thanks for the time you take to make this library available. It's very easy to use and the loaders look great.

I'm not sure if I'm missing some simple CSS or if this is a bug. I'm using Bootstrap 4, but on a minimal page I'm having a hard time resizing the loader without it moving horizontally.

### When scale is 1.0, everything is fine
![image](https://user-images.githubusercontent.com/107841/42790269-fed5f882-891e-11e8-8ac0-da8f0c33b786.png)

### When scale is below 1.0, the loader moves to the right
![image](https://user-images.githubusercontent.com/107841/42790302-29e2bcea-891f-11e8-9f5d-8ab786e6c11e.png)

### When scale is above 1.0, the loader moves to the left (off the screen)
![image](https://user-images.githubusercontent.com/107841/42790326-55b8094c-891f-11e8-8ef0-119dbd910e57.png)

If I just scale Y, the vertical size is impacted as expected without any movement. It seems to be when I scale X that the movement happens.

Any ideas? Details of my setup below.

application.scss
```scss
@import '~loaders.css/src/animations/line-scale.scss';
.loader-hidden {
  display: none;
}
.loader-active {
  display: block;
}
```

Versions
```
$ yarn list | grep loaders
├─ loaders.css@0.1.2
├─ react-loaders@3.0.1

webpack@3.12.0
sass-loader@6.0.7
```

**Comment by jonjaques** [comment]
4 years later -- thank your, but have expended very little effort, I am just an HTML wrapper for loaders.css project. I have discussed this with the author, but their project is similarly dead :) 

There are definitely better options today. `mantine.dev` comes to mind ;)

**Comment by aguynamedben** [comment]
👍  thanks thanks for being a part of the community in any capacity! 🙏
