### ISSUE TITLE
Shouldn't React 0.14 support have its own major version?

### ISSUE THREAD

**Issue by Enet4** [jonjaques/react-loaders#8]
It seems that the latest version (1.3.0) has made a sudden shift to React 0.14. Given that the package is usually installed with the default version range (`^`), an automatic package update with `npm update` will break a project still using React 0.13.x. This can be solved without much trouble, but it feels to me that a lot of confusion can be prevented if this version is instead modified into a major bump (2.0.0).

**Comment by jonjaques** [comment]
I'm not opposed to that. I've pushed `1.3.1` and `2.0` which should share the same interface (same props), but the former will support React 0.13.x.

Sorry for any inconvenience caused. :sweat_smile:
